### ISSUE TITLE
Add steampipe_connection column to all tables

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe-plugin-sdk#246]

**Comment by e-gineer** [comment]
What's the name of this column going to be?

```
steampipe_connection
sp_connection
_connection
other?
```

**Comment by kaidaguerre** [comment]
good question @e-gineer - whatever we choose will be a reserved name

I'm going with `steampipe_connection` for now but easy to change

maybe `_steampipe_connection` ?

**Comment by e-gineer** [comment]
@johnsmyth what do you think?

i think steampipe_connection is long, but probably best.

**Comment by johnsmyth** [comment]
its long, but its unambiguous.  I think `steampipe_connection` is fine.  @e-gineer at one point we talked about putting the connection name in a json `steampipe_context` field so that there would be a single column for steampipe-related info that we could extend later if needed - do you think we should consider that instead?

**Comment by johnsmyth** [comment]
Proposed:
- column name: `_ctx`
- format: `jsonb`
```json
{ 
  "connection_name":  "my_connection"
}
```
This will allow us to add other fields when requirements dictate, but still makes getting the connection name simple: `select _ctx ->> 'connection_name' from ...`
